"""
Resume ORM models — master resume and per-job tailored versions.
"""

from sqlalchemy import Column, String, Text, Integer, Boolean, JSON, ForeignKey
from app.models.base import Base, TimestampMixin, IdMixin


class MasterResume(Base, TimestampMixin, IdMixin):
    """Stores the user's master resume text and extracted skills."""

    __tablename__ = "master_resumes"

    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    raw_text = Column(Text, nullable=False)
    skills = Column(JSON, nullable=True)       # list[str] extracted skills
    experience = Column(JSON, nullable=True)   # list of structured experience entries
    is_active = Column(Boolean, default=True, nullable=False)

    def __repr__(self):
        return f"<MasterResume(id={self.id}, user_id={self.user_id}, active={self.is_active})>"


class ResumeVersion(Base, TimestampMixin, IdMixin):
    """Job-tailored resume version generated by ATS analysis."""

    __tablename__ = "resume_versions"

    master_id = Column(Integer, ForeignKey("master_resumes.id", ondelete="CASCADE"), nullable=False, index=True)
    job_id = Column(Integer, ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False, index=True)

    tailored_bullets = Column(JSON, nullable=True)    # list[str]
    tailored_summary = Column(Text, nullable=True)
    ats_improvements = Column(JSON, nullable=True)    # list[str] keyword additions

    def __repr__(self):
        return f"<ResumeVersion(id={self.id}, job_id={self.job_id})>"
